In [19]:
import pandas as pd
import json
import ast

In [115]:
Trail = pd.read_csv('hyperparameter_data.csv')

In [121]:
Trail.head()

,Unnamed: 0,hyperparameters,trial_id,parent_study_id
0,0,"{'base_score': 0.5, 'monotone_constraints': '(...",model_20211021-140355-3d2e0e259d-63c4e8d218,model_20211021-140355-3d2e0e259d
1,1,"{'monotone_constraints': '(0)', 'max_depth': 1...",model_20211021-140355-3d2e0e259d-02c72f84bf,model_20211021-140355-3d2e0e259d
2,2,"{'tree_method': 'auto', 'l2_regularization': 1...",model_20211021-140355-3d2e0e259d-3ac696ae29,model_20211021-140355-3d2e0e259d
3,3,"{'base_score': 0.5, 'column_sample_by_tree': 1...",model_20211021-140355-3d2e0e259d-7b1f8134d9,model_20211021-140355-3d2e0e259d
4,4,"{'column_sample_by_tree': 1.0, 'monotone_const...",model_20211021-140355-3d2e0e259d-8b7126772a,model_20211021-140355-3d2e0e259d

In [122]:
# Convert str to dict
Trail['hyperparameters'] = Trail['hyperparameters'].apply(lambda x: ast.literal_eval(x))

In [137]:
# Convert dict to columns
pd.DataFrame(list(Trail['hyperparameters'].values))

,base_score,monotone_constraints,column_sample_by_tree,column_sample_by_level,tree_method,subsample_ratio,max_count,l2_regularization,learn_rate,max_depth,min_child_weight,loss,maxCategories
0,0.5,(0),1.0,1.0,auto,1.0,168,1.0,0.077407,10,63,NaN,NaN
1,0.5,(0),1.0,1.0,auto,1.0,160,1.0,0.061635,11,37,NaN,NaN
2,0.5,(0),1.0,1.0,auto,1.0,366,1.0,0.071619,11,44,NaN,NaN
3,0.5,(0),1.0,1.0,auto,1.0,323,1.0,0.050162,11,61,none,NaN
4,0.5,(0),1.0,1.0,auto,1.0,274,1.0,0.098661,12,51,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3720,0.5,(0),1.0,1.0,auto,1.0,348,1.0,0.081830,11,68,NaN,NaN
3721,0.5,(0),1.0,1.0,auto,1.0,338,1.0,0.074883,10,35,NaN,NaN
3722,0.5,(0),1.0,1.0,auto,1.0,137,1.0,0.054669,11,57,NaN,NaN
3723,0.5,(0),1.0,1.0,auto,1.0,348,1.0,0.061291,11,32,NaN,-2.0
3724,0.5,(0),1.0,1.0,auto,1.0,338,1.0,0.061523,11,69,NaN,NaN

In [42]:
# Concat the data
hyperparameter = pd.concat([Trail,pd.DataFrame(list(Trail['hyperparameters'].values))],axis=1 )

In [138]:
hyperparameter.info()

# Found 2 columns with missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3725 entries, 0 to 3724
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              3725 non-null   int64
 1   hyperparameters         3725 non-null   object
 2   trial_id                3725 non-null   object
 3   parent_study_id         3725 non-null   object
 4   base_score              3725 non-null   float64
 5   monotone_constraints    3725 non-null   object
 6   column_sample_by_tree   3725 non-null   float64
 7   column_sample_by_level  3725 non-null   float64
 8   tree_method             3725 non-null   object
 9   subsample_ratio         3725 non-null   float64
 10  max_count               3725 non-null   int64
 11  l2_regularization       3725 non-null   float64
 12  learn_rate              3725 non-null   float64
 13  max_depth               3725 non-null   int64
 14  min_child_weight        3725 non-null   int64
 15  loss                    300 non-null    object
 16  maxCategories           249 non-null    float64
 17  train_result            3725 non-null   object
 18  test_result             3725 non-null   object
dtypes: float64(7), int64(4), object(8)
memory usage: 553.1+ KB

In [105]:
# Get model performance from learning summaries

hyperparameter['train_result']=None
hyperparameter['test_result']=None

for i in range(len(hyperparameter)):
    file_name = 'C:\\Users\\cheng\\Desktop\\235\\data\\learning_summaries\\' + hyperparameter['trial_id'][i] + '_' + hyperparameter['parent_study_id'][i] +'.csv'
    trail = pd.read_csv(file_name)
    # Remove early stopped iterations
    trail = trail[trail.train_summaries != 0]
    # Sub-in with the end result
    hyperparameter.loc[i,['train_result']] = trail.iloc[-1].train_summaries
    hyperparameter.loc[i,['test_result']] = trail.iloc[-1].test_summaries

In [111]:
hyperparameter.head()

,Unnamed: 0,hyperparameters,trial_id,parent_study_id,base_score,monotone_constraints,column_sample_by_tree,column_sample_by_level,tree_method,subsample_ratio,max_count,l2_regularization,learn_rate,max_depth,min_child_weight,loss,maxCategories,train_result,test_result
0,0,"{'base_score': 0.5, 'monotone_constraints': '(...",model_20211021-140355-3d2e0e259d-63c4e8d218,model_20211021-140355-3d2e0e259d,0.5,(0),1.0,1.0,auto,1.0,168,1.0,0.077407,10,63,NaN,NaN,170.942551,195.144424
1,1,"{'monotone_constraints': '(0)', 'max_depth': 1...",model_20211021-140355-3d2e0e259d-02c72f84bf,model_20211021-140355-3d2e0e259d,0.5,(0),1.0,1.0,auto,1.0,160,1.0,0.061635,11,37,NaN,NaN,167.232773,195.339005
2,2,"{'tree_method': 'auto', 'l2_regularization': 1...",model_20211021-140355-3d2e0e259d-3ac696ae29,model_20211021-140355-3d2e0e259d,0.5,(0),1.0,1.0,auto,1.0,366,1.0,0.071619,11,44,NaN,NaN,157.836639,193.886414
3,3,"{'base_score': 0.5, 'column_sample_by_tree': 1...",model_20211021-140355-3d2e0e259d-7b1f8134d9,model_20211021-140355-3d2e0e259d,0.5,(0),1.0,1.0,auto,1.0,323,1.0,0.050162,11,61,none,NaN,163.039749,194.246948
4,4,"{'column_sample_by_tree': 1.0, 'monotone_const...",model_20211021-140355-3d2e0e259d-8b7126772a,model_20211021-140355-3d2e0e259d,0.5,(0),1.0,1.0,auto,1.0,274,1.0,0.098661,12,51,NaN,NaN,152.599945,194.235336

In [113]:
# Output cleaned data
hyperparameter.loc[:,'trial_id':].to_csv('Cleaned dataset V1.csv')